name: Deploy cyclonedx-bom to Crates.io
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "cyclonedx-bom release type (major, minor, patch)"
        required: true
        default: "patch"
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ steps.version.outputs.TAG_NAME }}
    steps:
      - name: JQ
        run: |
          sudo apt-get install -y jq
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo bump
        run: |
          cargo install cargo-edit
          cargo set-version --package cyclonedx-bom --bump ${{ github.event.inputs.releaseType }}
      - name: Set new version and tag name
        id: version
        run: |
          CARGO_VERSION=$(cargo metadata | jq -r '.packages[] | select(.name == "cyclonedx-bom") | .version')
          echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_OUTPUT
          TAG_NAME=cyclonedx-bom-$CARGO_VERSION
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
      - name: Build one time, for sanity
        run: cargo build
      # - name: Publish
      #   run: cargo publish --token ${{ secrets.CARGO_API_KEY }} --package cyclonedx-bom --verbose --allow-dirty
      - name: Configure git and add files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "New development bump of cyclonedx-bom to ${{steps.version.outputs.CARGO_VERSION}}"
          git tag -a ${{ steps.version.outputs.TAG_NAME }} -m "cyclonedx-bom ${{ steps.version.outputs.CARGO_VERSION }} release"
          git push --follow-tags

  build-prod:
    name: Build prod - ${{ matrix.platform.name }}
    needs: deploy
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: cargo-cyclonedx
            zip: cargo-cyclonedx-linux-amd64.tar.gz
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            bin: cargo-cyclonedx.exe
            zip: cargo-cyclonedx-Win-x86_64.zip
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
            bin: cargo-cyclonedx
            zip: cargo-cyclonedx-Darwin-x86_64.tar.gz
          - name: macos-aarch64
            runner: macos-latest
            target: aarch64-apple-darwin
            bin: cargo-cyclonedx
            zip: cargo-cyclonedx-Darwin-aarch64.tar.gz
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout release tag
        run: |
          echo "${{ needs.deploy.outputs.TAG_NAME }}"
          git checkout ${{ needs.deploy.outputs.TAG_NAME }}
          git status
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"
      - uses: Swatinem/rust-cache@v2
      - name: Build release binaries
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
      - name: Package as archives
        id: zip
        shell: bash
        run: |
          mkdir out
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            mv cargo-cyclonedx ${{ matrix.platform.bin }}
            7z a ../../../out/${{ matrix.platform.zip }}.zip ${{ matrix.platform.bin }}
          else
            tar czvf ../../../out/${{ matrix.platform.zip }}.tar.gz ${{ matrix.platform.bin }}
          fi
          cd -
          shasum -a 256 ${{ matrix.platform.name }} > out/${{ matrix.platform.zip }}.sha256
          ls -lh out
      - uses: actions/upload-artifact@v3
        with:
          name: cyclonedx-${{ matrix.platform.os_name }}
          path: "out/*"

  release:
    needs: [deploy, build-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Review and move artifacts
        run: |
          mkdir dist
          find artifacts -type f -exec mv {} dist \;
          ls -lh dist
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "cyclonedx-bom-${{ needs.deploy.outputs.TAG_NAME }}"
          tag_name: ${{ needs.deploy.outputs.TAG_NAME }}
          files: "dist/*"
